#!/bin/sh

. /lib/functions.sh

board=$(board_name)

[ "$board" = "keenetic,kn-3410" ] || exit 0

# Включаем Wi-Fi и открытые сети
uci set wireless.@wifi-iface[0].ssid='Test'
uci set wireless.@wifi-iface[0].encryption='none'
uci set wireless.@wifi-iface[0].disabled='0'

uci set wireless.@wifi-iface[1].ssid='Test5G'
uci set wireless.@wifi-iface[1].encryption='none'
uci set wireless.@wifi-iface[1].disabled='0'

# Настраиваем LED-индикаторы через system
uci set system.@led[0]=led
uci set system.@led[0].name='wifi2'
uci set system.@led[0].sysfs='green:wifi2'
uci set system.@led[0].trigger='netdev'
uci set system.@led[0].dev='wlan0'
uci set system.@led[0].mode='link tx rx'

uci set system.@led[1]=led
uci set system.@led[1].name='wifi5'
uci set system.@led[1].sysfs='green:wifi5'
uci set system.@led[1].trigger='netdev'
uci set system.@led[1].dev='wlan1'
uci set system.@led[1].mode='link tx rx'

uci commit wireless
uci commit system

exit 0
